### ISSUE TITLE
Checks appear to be hung

### ISSUE THREAD

**Issue by hiimbex** [swinton/linter-alex#10]
See: https://github.com/probot/probot.github.io/pull/234/checks?check_run_id=12410918 and
https://github.com/probot/probot.github.io/pull/235/checks for 'In progress checks' that were started respectively 2 hours and 20 minutes ago

**Comment by swinton** [comment]
Sorry about this!

I believe it's because Alex has found 98 issues, and the API only allows 50 per-request:

```
{"message":"Invalid request.\n\n\"end_line\", \"start_line\" weren't supplied.\nNo more than 50 items are allowed; 98 were supplied.","documentation_url":"https://developer.github.com/v3/checks/runs/#update-a-check-run"}
```

I'll have to rework [this part](https://github.com/swinton/linter-alex/blob/28ef1dd066c20236cc6c6444c55d9e4b24b15f55/index.js#L64-L73) to break up annotations > 50 into multiple `PATCH` requests:

 
https://github.com/swinton/linter-alex/blob/28ef1dd066c20236cc6c6444c55d9e4b24b15f55/index.js#L64-L73
